name: Compare to baseline
on: issue_comment

permissions:
  issues: write
  pull-requests: write
  contents: read
  
jobs:
  baseline-comparision:
    runs-on: ubuntu-latest
    # only on pull request comments
    if: (github.event.issue.pull_request != null) && contains(github.event.comment.body, '/wandb')
    steps:
      - name: Copy Repository Contents
        uses: actions/checkout@v3
        
      - name: see payload # this step is for debugging purposes only, so you can see the payload. 
        run: echo "PAYLOAD:\n${PAYLOAD}\n"
        env:
          PAYLOAD: ${{ toJSON(github.event) }}
        
      - name: Parse String
        id: parse-string
        run: |
          # Extract the string after the keyword using regular expressions
          string=$(echo "${{ github.event.comment.body }}" | grep -oP '(?<=/wandb\s)[^\s]*')

          # Set the extracted string as an output
          echo "STRING_TO_PARSE=${string}" >> "$GITHUB_OUTPUT"

      - name: Run comparision script
        run: |
          pip install wandb ghapi
          python compare_to_baseline.py
        env:
          RUN_ID_TO_COMPARE: ${{ steps.parse-string.outputs.string_to_parse }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }} 
          WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
          
