name: Label Bug
on: issue_comment

permissions:
  issues: write
  pull-requests: write
  
env:
  MAGIC_COMMENT: "/bug"
  LABEL: ':bug: bug'
  
jobs:
  label-comment:
    # only on pull request comments
    if: ${{ github.event.issue.pull_request }} && contains(github.event.comment.body, env.MAGIC_COMMENT)
    runs-on: ubuntu-latest
    steps:    
    - name: Get label
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.getLabel({
            owner: context.repo.owner,
            repo: context.repo.repo,
            name: "${{ env.LABEL }}"
          })
      
    - name: Create label (only if label does not exist)
      uses: actions/github-script@v6
      # create label only if the previous step failed 
      if: ${{ failure() }}
      with:
        script: |
          github.rest.issues.createLabel({
            owner: context.repo.owner,
            repo: context.repo.repo,
            name: "${{ env.LABEL }}"
          })
          
    - name: Add label
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.addLabels({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            labels: ["${{ env.LABEL }}"]
          })
