on: push

jobs:
  secrets:
    runs-on: ubuntu-latest
    steps:
    - run: |
        import os
        print(f"Length of secret: {len(os.getenv('MY_SECRET_VAR'))}")
      
      shell: python
      env:
        MY_SECRET_VAR: ${{ secrets.MY_FIRST_SECRET }}
    
    
